# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.0.1
maven_group = com.wayward
archives_name = wayward
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.26-beta
