modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "wayward"
version = "${version}"
displayName = "Wayward"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
# logoFile = "assets/wayward/icon.png"

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[26,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[26.,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "wayward.mixins.json"
